# DO NOT EDIT THIS FILE

SUBMIT  := $(wildcard src/main/java/org/cis1200/*.java src/test/java/org/cis1200/*.java PLAN.txt)

EXCLUDE := \
	src/main/java/org/cis1200/Broadcast.java \
	src/main/java/org/cis1200/Command.java \
	src/main/java/org/cis1200/CommandParser.java \
	src/main/java/org/cis1200/ServerBackend.java \
	src/main/java/org/cis1200/ServerResponse.java \
	src/main/java/org/cis1200/ServerMain.java \
	src/main/java/org/cis1200/ServerModelApi.java \
	src/test/java/org/cis1200/Task2Test.java \
	src/test/java/org/cis1200/Task4Test.java \
	src/test/java/org/cis1200/Task3Test.java \
	src/test/java/org/cis1200/Task5Test.java

SUBMIT  := $(filter-out $(EXCLUDE),$(SUBMIT))

HWNAME := hw07
ts := $(shell /bin/date "+%Y-%m-%d-%H:%M:%S")

ZIPNAME := $(HWNAME)-submit($(ts)).zip

.PHONY: all compile run zip test checkstyle format clean

all:	

compile:
	mvn compile

run: compile
	mvn exec:java

zip: $(SUBMIT)
	zip -j '$(ZIPNAME)' $(SUBMIT)

test: 
	mvn test

test-stack-trace:
	mvn -DtrimStackTrace=false test

checkstyle: 
	mvn checkstyle:checkstyle

format:
	mvn formatter:format

clean:
	rm -f src/*.class bin/* test/*.class
	rm -rf *.zip
	mvn clean
